configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lixforg%2Fmytestsdk3-c3ff2b1b939259458df61611b1dbe652a258d72dbbd84adaa35e39e11c14f24f.yml
openapi_spec_hash: ad56efe83b7e0fbfdd11ecf42a42b06e
config_hash: 47bbac0f9833688eba46e0a8cbcd1f91
